export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const GET_POST_FAILURE = "GET_POST_FAILURE";
export const SUCCESS_FETCH_POST = "SUCCESS_FETCH_POST";
export const FETCH_POSTS = "FETCH_POSTS";
export const NEW_POST = "NEW_POST";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
